app/Models/MovieList.php, app/Models/lists.php, database/migrations/2025_01_28_110447_create_lists_table.php
- Added model for lists
- Added migration for all rows in lists table
=> feat: create list migration

resources/css/app.css
- remove some breeze generated code
- import and add our font
i don't think there's anything else we need? since we're mostly using tailwind predefined stuff
closes #46
=> feat: configure tailwind theme

app/Models/Genre.php, database/migrations/2025_01_28_171411_create_genre_table.php, package-lock.json
created genre model and migration
close #42
=> create genre model and migration

database/migrations/0001_01_01_000000_create_users_table.php, package-lock.json
change the users table to the correct rows
closes #36
=> feat: change users table

package-lock.json
after this we should always use this lock file and accept changes from main when rebasing
=> chore: fix lock file

app/Models/Movie.php, app/Models/MovieList.php, database/migrations/2025_01_29_224410_create_list_movie_table.php
=> feat: create Many-to-Many Relationship Between Movies and Lists

composer.json
- add a script to easily format all files in the project
usage:
```bash
composer run format
```
=> feat: add `format` script

app/Http/Controllers/ListController.php
closes #143
generate a resource controller for lists
=> feat: create list controller

app/Models/Movie.php, database/factories/MovieFactory.php, database/seeders/DatabaseSeeder.php
- This PR includes factory and seeds for the movies table.
- For the poster and cover_image columns, i have setup arrays with 10 image urls for each column to generate the images correctly. 
closes #149
=> feat: create movies factory

app/Http/Controllers/MovieController.php
=> feat: create controller for movie

resources/views/components/movie.blade.php
closes #53 
- takes in title, rating, image and a link
- added a little hover effect to give a visual cue that it's clickable
- clamped the text at 3 lines
**example usage**
```blade
<x-movie
title="The Worst Person in The World"
rating="7.6"
image="https://m.media-amazon.com/images/M/MV5BZGEyYzBiYmItZDM4OC00NTdmLWJlYzctODdiM2E2MjZmYTU2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
link=""
class="w-40"
/>
<x-movie
title="The Worst Person in The World hello here is some more text to see how it looks"
rating="7.6"
image="https://m.media-amazon.com/images/M/MV5BZGEyYzBiYmItZDM4OC00NTdmLWJlYzctODdiM2E2MjZmYTU2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
link=""
class="w-40"
/>
```
https://github.com/user-attachments/assets/b9df1338-5a28-4137-a41b-3c86c59647d7
=> feat: create movie component

resources/views/components/list.blade.php, resources/views/home.blade.php
realized i forgot to make this component a link before. i also changed the alt attribute, added a little hover effect and clamped the text to match what i'm working on with the movie component #206
=> fix: add link to list component

database/factories/UserFactory.php, database/seeders/DatabaseSeeder.php
- This PR includes factory and seeds for the users table
- It generates 10 users
closes #145
=> feat: add factory and seed for users table

app/Http/Controllers/ReviewController.php
=> feat: add review controller

resources/views/auth/log-in.blade.php, routes/web.php
=> feat: log in route

app/Http/Controllers/ReportController.php
Add report controller
closes #141
=> feat: add report controller

app/Http/Controllers/UserController.php
- Added user controller
closes #138
=> feat: add user controller

resources/views/auth/sign-up.blade.php, routes/web.php
=> feat: sign up route

resources/views/review.blade.php, routes/web.php
=> feat: add review view and route

resources/views/profile.blade.php, routes/web.php
closes #74
my suggestion is to just go with `/u` for users and `/m` for movies since we will use the username and movie title to keep the urls short and clean
- `/u/ellska`
=> feat: profile route

resources/views/movie.blade.php, routes/web.php
closes #89 
- i suggest to go with just `m` to keep it short and simple
- i suggest to use both the `id` (to uniquely identify the movie)
- and the `title` for improved ux
- `/m/1/the-worst-person-in-the-world`
=> feat: movie route

resources/views/reviews.blade.php, routes/web.php
=> feat: add reviews view and route

resources/views/lists.blade.php, routes/web.php
=> feat: add lists view and route

resources/views/components/input/error.blade.php, resources/views/components/input/password.blade.php, resources/views/components/input/text.blade.php
closes #272 
- create `input.error` component
- add it to the existing inputs
=> feat: input error

resources/views/components/button.blade.php, resources/views/components/input/password.blade.php, resources/views/components/search.blade.php
i realized we're going to need a way to change the type of a button (`button` and `submit`). this changes the logic so that if you pass in an `href` its going to render a link instead of a button. and also allows to pass in attributes so that we can set type outside of the component
=> fix: button type

app/utils/helpers.php, composer.json, resources/views/components/review.blade.php
After pulling these changes, please run the following command to update the autoload files:
```blade
composer dump-autoload
```
This is necessary to ensure that the new helper function in the helpers.php file are correctly included and available throughout the application. 
I have added a helper function called `formatDate` to provide a reusable way to format dates.
props [
'title',
'description',
'created_at',
'rating',
'image',
'link',
'username'
]
example usage:
```blade 
<x-review
title="The Worst Person in The World"
description="A young  asldkj"
rating="7.6"
created_at="2025-02-22"
username="David Dyberg"
link="linkUrl"
image="imageUrl"
/>
```
https://github.com/user-attachments/assets/77f86d7c-a68e-40a6-93d0-adc3baaa8c8b
closes #55
=> feat: create review component

resources/css/app.css, resources/views/auth/sign-up.blade.php, resources/views/components/input/password.blade.php, resources/views/components/layout.blade.php
closes #222
- create static sign up page
- adjust layout to take in classes to main
- add some padding to layout to account for the fixed header
=> feat: sign up view

app/Http/Controllers/ReviewController.php, app/Models/Review.php
This PR includes the fetch data logic for a single review. It passed the data from the controller to the review view. I also needed to modify the review model to set up the correct relations to movie and user.
Example data:
closes #288
=> feat: fetch review view data

app/Http/Controllers/Auth/RegisteredUserController.php, app/Models/User.php, resources/views/auth/sign-up.blade.php, resources/views/components/input/text.blade.php, routes/auth.php
closes #224 
- change places where we forgot to change `name` to `username`
- update the inputs to pass data to the controller
- update inputs to handle errors from the form
go to `/sign-up` and you should be able to create an account!
https://github.com/user-attachments/assets/d8ddd2f5-bc73-4723-8895-c6312431f32a
=> feat: sign up functionality

app/Models/MovieList.php, app/Models/User.php, database/migrations/2025_01_30_134914_create_list_users_table.php
Changed to the correct name on list_user table.
=> fix: change to correct name on list_user pivot table

app/Http/Controllers/Auth/RegisteredUserController.php, database/factories/UserFactory.php
- Fixed the user factory to not generate username with spaces.
- Added validation in sign-up to not allow users to have username with spaces
=> fix: username seed to not include space & validate sign-up to not allow username to have space.

resources/views/components/header.blade.php, resources/views/components/layout.blade.php, resources/views/components/search.blade.php, resources/views/home.blade.php
closes #48 
- displays a log in button or a profile button depending on if you're logged in or not
- added some more content on the home page just to show that the scroll is working
=> feat: create header

app/Http/Controllers/ListController.php
This PR includes the logic for fetching all lists from a user. I also made so the movie data within each list can be loaded.
closes #292
=> feat: fetch all lists related to a user

resources/views/components/header.blade.php, resources/views/components/layout.blade.php, resources/views/components/section.blade.php
- hovering something with the scale effect would cause it to end up on top of the header
- fixed a faulty breakpoint for the header layout padding
- remove extra spacing at the end of the list
https://github.com/user-attachments/assets/b087dbf7-0f1b-475c-996a-e5cc01184b7a
=> fix: section bug

routes/auth.php
This update introduces a log-out route to allow authenticated users to securely sign out of their accounts.
closes #342
=> feat: add log-out route

resources/views/auth/sign-up.blade.php
@ADchasacademy noticed i didn't follow the new design! removed the arrow and added a little hover effect
=> fix: remove sign up arrow

app/Http/Controllers/Auth/AuthenticatedSessionController.php, app/Http/Requests/Auth/LoginRequest.php
This update implements the login functionality, allowing users to authenticate securely.  
- 🔐 Added authentication logic using Laravel's `Auth` system.   
- ⚠️ Displayed error messages for invalid credentials.  
- 🔄 Implemented session regeneration after successful login for security.  
closes #340
=> feat: add login feature

resources/views/components/input/date.blade.php, resources/views/components/input/password.blade.php, resources/views/components/input/text.blade.php, resources/views/components/input/textarea.blade.php
realized the inputs have a lighter color when used in a modal. this updates all of the existing inputs to get the option of choosing a lighter color
also fixed some issues with the text area
=> fix: input color

app/Models/Movie.php, app/Models/Review.php
closes #356 
- create a function that calculates and updates `rating_average` and `rating_amount` in the `movies` table
- run it every time a review is created, updated or deleted
- create a new review for movie with id `1` in `tinker`
- reload the data in the database and the fields in the row has been updated
https://github.com/user-attachments/assets/86227df3-c5d5-408e-abe4-3918b4b130ba
=> feat: create `updateRating` function in `Review` model

resources/views/components/section.blade.php
=> fix: remove section padding on desktop

app/Http/Controllers/ProfileController.php, app/Models/Review.php, app/Models/User.php, resources/views/profile.blade.php
closes #99 
- get the users 4 most recent reviews
- change the header title depending on if it's the current user or someone else
- 1st user doesn't have any reviews
- 2nd user is me (currently logged in)
- 3rd is someone else
https://github.com/user-attachments/assets/5c62e055-3ae3-4be0-b610-5e35fd6e7e48
_note:_ the review component is a bit broken but fixed in #349
=> feat: reviews on profile view

database/seeders/DatabaseSeeder.php
- It gives each move 1-7 genres from the genre table
closes #376
=> feat: add seeds for genre_movie pivot table

app/Http/Controllers/ReviewController.php, resources/views/components/section-header/back-link.blade.php, resources/views/reviews.blade.php
- It checks if user is me, and displays "My reviews", or "@usernames reviews" depending on that
- In section-header component, i changed the extraLabel to optional.
Note: I did not include the search bar because it is not prioritized, i made a separate issue for that, issue 375.
closes #108
=> feat: create content reviews view

resources/views/review.blade.php
- The backLabel checks if the user previously came from the movie or profile route.
- Fix: To fix the positioning on the ellipsis icon, I made 2 versions of it depending on screen size breakpoints
closes #109
=> feat: add content on review view

app/Http/Middleware/AdminMiddleware.php, app/Models/User.php, docker-compose.yml, routes/web.php
This PR adds a admin middleware so others cant get to the admin routes and they are send back to homepage
=> feat: AdminMiddleware

app/Http/Controllers/ListController.php, app/Models/MovieList.php, resources/views/components/header.blade.php, resources/views/components/modal/base.blade.php, resources/views/lists.blade.php, routes/web.php
closes #114 
- uses the modal components
- form with title and description
- displays validation errors in the form
- create the `store` function in `ListController`
- adds a new route with the `auth` middleware
- create "create list" button. it will be moved once there is more content on the page
- throws a general error message in case of an unexpected error that is displayed under the form
go to `/u/{username}/lists` and try to create a new list. note that you have to be logged in or you will be redirected to the log in page (you will not be able to see the button if you're not logged in when this page is done)
=> feat: create list

app/Http/Controllers/ProfileController.php, resources/views/profile.blade.php
closes #98
- renders the four latest created user lists
- title
- 4 latest added movies
- if the user has no lists this section won't be rendered
=> feat: add lists on profile view

app/Http/Controllers/ListController.php, app/Http/Controllers/MovieController.php, app/Http/Controllers/ReviewController.php, app/Models/MovieList.php, resources/views/components/header.blade.php, resources/views/components/input/rating.blade.php, resources/views/components/modal/base.blade.php, resources/views/lists.blade.php, resources/views/movie.blade.php, routes/web.php
closes #110 
- uses the modal components
- form with rating and content
- displays validation errors in the form
- create the `store` function in `ReviewController`
- adds a new route with the `auth` middleware
- create "write a review" button. it will be moved once there is more content on the page
- fetches the movie to display the data
- throws a general error message in case of an unexpected error that is displayed under the form
go to a movie and try to write a new review. you should be redirected to the review page and see your review. note that you have to be logged in or you will be redirected to the log in page
=> feat: create review modal

app/Http/Controllers/ReviewController.php
accidentally left this here while debugging
=> fix: remove dd in review store

app/Http/Controllers/ListController.php, resources/views/list.blade.php
closes #115
- render content on list view
- update fetched data
=> feat: list view

app/Http/Controllers/ProfileController.php, app/Models/User.php, resources/views/components/input/date.blade.php, resources/views/profile.blade.php, routes/web.php
closes #105
- modal with date input and error handling
- `ban` method in `ProfileController`
- `isBanned` method on `User` model
https://github.com/user-attachments/assets/988e9454-e515-41a4-9e50-e3c5d2449c3a
=> feat: ban user modal

resources/views/components/create-list-modal.blade.php, resources/views/lists.blade.php, resources/views/profile.blade.php
closes #417
- move create list modal to a separate file
- add it to the profile view
- add a button on the current user empty state
https://github.com/user-attachments/assets/9fadbf1f-3008-4072-850a-41351ade6cb9
=> fix: profile empty state

app/Http/Controllers/ReportController.php, resources/views/profile.blade.php, routes/web.php
closes #104 
- modal for reporting users with error handling
- update the `store` method in `ReportController`
https://github.com/user-attachments/assets/517fab67-a8b1-4e95-9cfa-18ae86b1058f
=> feat: report user modal

app/Http/Controllers/ListController.php, app/Http/Controllers/ProfileController.php, resources/views/components/empty-state.blade.php, resources/views/lists.blade.php
closes #113 
https://github.com/user-attachments/assets/f0fc052d-e67e-4311-b274-5c46d8168fd1
=> feat: create content on lists view

resources/views/list.blade.php
i forgot to add this check when creating the page
=> fix: add movie button showing on someone else's list

resources/views/components/section-header/back-link.blade.php, resources/views/components/section-header/link.blade.php
https://github.com/user-attachments/assets/b57ffe98-f61c-4a89-9261-e17a0bf4284c
https://github.com/user-attachments/assets/39068a7f-48be-4fb4-8bc8-b4081492c53b
=> fix: section header width

resources/views/home.blade.php
closes #437 
[![Image from Gyazo](https://i.gyazo.com/2811697e3e59d47dbfa6b545e161aa53.png)](https://gyazo.com/2811697e3e59d47dbfa6b545e161aa53)
=> refact: replace block with flex (fixing landing page)

resources/views/lists.blade.php
[![Image from Gyazo](https://i.gyazo.com/e4b481901ece416dc0b74e558a639fc9.png)](https://gyazo.com/e4b481901ece416dc0b74e558a639fc9)
noticed this, removed it with this change
=> fix: remove duplicated 'create list' button

app/Http/Controllers/ListController.php, app/Http/Controllers/MovieController.php, resources/views/components/input/error.blade.php, resources/views/components/section.blade.php, resources/views/movie.blade.php, routes/web.php
closes #132 
- modal showing user lists and "add to list" button
- shows "create list" button if the user has no lists
- ensures movies can't be added twice to the same list
https://github.com/user-attachments/assets/97e5850c-c79f-4150-a624-15b47a05a9ad
=> feat: add to list

database/factories/MovieFactory.php, database/seeders/DatabaseSeeder.php
just adding some higher quality images before the demo. stole all of them from here https://www.imdb.com/imdbpicks/staff-picks/
=> refactor: higher quality images in `MovieFactory`
