chas-academy/u04-imdb-klon-grupp2

- .github/reviewer-lottery.yml
- .github/workflows/assign-reviewers.yml
closes #11 
sets up a github action to run and assign two random people for review. i had to use a personal access token since we can't change permissions of this repository
> ci: set up assign reviewers github action

- resources/views/components/poster.blade.php
closes #52 
- creates a poster component that will be rounded by default but it can be turned of (for the list component)
- it will always keep the correct aspect ratio and make sure the image isn't stretched weirdly if it doesn't fit
example usage:
```php
<x-poster
src="https://m.media-amazon.com/images/M/MV5BZGEyYzBiYmItZDM4OC00NTdmLWJlYzctODdiM2E2MjZmYTU2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
class="max-w-sm"
/>
```
if no source is given it will show a placeholder (eg in empty lists):
> feat: poster component

- resources/views/components/rating.blade.php
closes #56 
- supports 3 sizes
- takes in a dynamic rating
- can be bold or not
example usage:
```php
<x-rating rating="5.6" size="sm" />
<x-rating rating="8" size="md" />
<x-rating rating="9.3" size="lg" bold />
```
> feat: create rating component

- resources/css/app.css
- resources/views/components/button.blade.php
closes #51 
- 3 variants
- 2 sizes
- can be either a button (with `onclick`) or link (with `href`)
- icon variants must provide a label for screen readers
- add focus outlines for accessibility
example usage:
```blade
<x-button>Click me</x-button>
<x-button size="sm">Click me</x-button>
<x-button variant="secondary">Click me</x-button>
<x-button variant="secondary" size="sm">Click me</x-button>
<x-button variant="icon" srLabel="Click me">
<x-lucide-x class="size-4" />
</x-button>
```
https://github.com/user-attachments/assets/7addaef0-52d4-4869-b752-cb474656ea57
_note: the cursor is a pointer, it's just when i screen record it's not picking up_
> feat: create button component

- resources/views/components/avatar.blade.php
closes #68 
- has 3 sizes
- optionally takes an image
**example usage:**
```blade
<x-avatar size="md" />
<x-avatar
size="md"
image="https://images.unsplash.com/photo-1..."
alt="usernames avatar"
/>
```
> feat: create avatar component

- resources/views/components/search.blade.php
closes #66 
- clears the input when clicking the x button with alpine.js
**example usage:**
```blade
<x-search placeholder="Search..." id="search" />
```
https://github.com/user-attachments/assets/a19baec8-4d96-4ac3-b766-f460c0d36b95
_note:_ we will need to make adjustments to the behavior of the x button. we sometimes use it to close out of the entire search bar in the design. but i think this is out of scope for this issue and i'll create a new one
> feat: create search component

- app/Models/Movie.php
- app/Models/MovieList.php
- database/migrations/2025_01_29_224410_create_list_movie_table.php
This update introduces a **composite unique key** on the `list_id` and `movie_id` columns to ensure that the same movie cannot be added multiple times to the same list.
The following constraint has been added in the migration:
```php
$table->unique(['list_id', 'movie_id']);
```
Without this constraint, duplicate movie entries could be inserted into the same list, leading to data inconsistencies and incorrect application behavior. By enforcing this rule at the database level, we reduce the need for additional validation in the application code.
With this constraint in place, any attempt to insert a duplicate entry will result in an **SQL integrity constraint violation error**. To handle this properly, future code should:
- **Catch the database error** and return a user-friendly message.
- …
> Fix: Prevent Duplicate Movie Entries in a List

- app/Models/Genre.php
- app/Models/Movie.php
- app/Models/MovieList.php
- database/migrations/2025_01_31_152355_create_genre_movie_table.php
This update introduces a pivot table to establish a **many-to-many** relationship between movies and genres. To ensure data integrity, a composite unique key has been added to prevent duplicate entries for the same movie-genre pair.
The following constraint has been added in the migration:
```php
$table->unique(['movie_id', 'genre_id']); 
```
A movie can belong to multiple genres, and a genre can be associated with multiple movies. Using a **pivot table** allows efficient handling of this relationship while preventing redundant entries. The composite unique key ensures that each movie-genre combination is stored only once, avoiding duplicate associations.
With this constraint in place:
- Any attempt to insert a duplicate movie-genre entry will result in an SQL integrity constraint …
> feat: Add many to many relationship between Genre and Movie

- resources/views/components/input/label.blade.php
closes #207 
- simple label for our inputs
- scoped it under `/input` for organization purposes
```blade
<x-input.label for="my-input">label</x-input.label>
```
> feat: input label

- resources/views/components/input/password.blade.php
closes #209 
- can toggle visibility of the password
```blade
<x-input.password name="password" label="Password" placeholder="Password" />
```
https://github.com/user-attachments/assets/fc687b83-4a9c-452f-8a3c-dcc7b251fb13
> feat: password input

- app/Http/Controllers/Auth/AuthenticatedSessionController.php
- app/Http/Controllers/Auth/RegisteredUserController.php
- app/Http/Controllers/ListController.php
- app/Http/Controllers/MovieController.php
- app/Http/Controllers/ProfileController.php
- app/Http/Controllers/ReviewController.php
- routes/auth.php
- routes/web.php
closes #281 
when we created all of our routes we didn't connect them to the intended controller. this connects all routes to their respective controllers. as well as provides some organization. i decided to organize with controller groups, except for the admin routes which are kept together to ensure all of them are behind the admin middleware (that doesn't exist yet)
i also think we will need to create an admin controller to handle all of the admin specific pages and actions
tldr:
- group routes into controller groups
- group admin routes into a group with admin middleware
- move views from routes to controllers
- move auth related routes into `routes/auth.php`
- comment out auth related routes we have not yet implemented
> refactor: connect routes to controllers

- resources/css/app.css
- resources/views/components/section.blade.php
closes #58 
- supports setting different amounts columns at different breakpoints
- it expects a base size and can then take any or all of these tailwind breakpoints: `sm`, `md`, `lg`
- how it works is that the column prop provided will be transformed into an css variable that will then be used together with tailwinds breakpoints to change the amount of columns
- can be scrollable on mobile
- will switch back to non scrollable variant at `sm:`
- takes a slot where any item can be rendered, the sizing of the item will be dynamic according to the grid
```blade
<x-section :columns="[3, 'sm' => 4, 'lg' => 6]" scrollableOnMobile>
@foreach ($movies as $movie)
<x-movie
title="{{ $movie['title'] }}"
rating="{{ $movie['rating'] }}"
image="{{ $movie['cover'] }}"
/>
@endforeach
</x-section>
``` …
> feat: section component

- resources/views/components/profile-simplified.blade.php
It takes in these props 
- username
- image
- size
```blade 
<x-profile-simplified
username="Jane Doe"
size="md"
image="https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=2864&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
/> 
```
closes #218
> feat: add profile simplified compoenent

- composer.json
- composer.lock
- resources/views/components/button.blade.php
- resources/views/components/layout.blade.php
- resources/views/components/list.blade.php
- resources/views/components/movie.blade.php
- install the package [twMerge](https://github.com/gehrisandro/tailwind-merge-laravel)
- update the places where we merge component classes with the attribute class
> TailwindMerge for Laravel allows you to merge multiple [Tailwind CSS](https://tailwindcss.com/) classes and automatically resolves conflicts between classes by removing classes conflicting with a class defined later. This is especially helpful when you want to override Tailwind CSS classes in your Blade components.
```blade
<x-button class="hidden sm:inline-flex">
should be hidden on mobile
</x-button>
<x-button class="sm:hidden">should be hidden on desktop</x-button>
```
**before `twMerge`**
https://github.com/user-attachments/assets/f635a6c3-f9af-4ab2-a675-540a79b847a9
**after `twMerge`** …
> feat: add `twMerge`

- app/Http/Controllers/ListController.php
- database/seeders/DatabaseSeeder.php
- Seeded list_user table: Each user is randomly attached to 1-5 lists.
- Seeded list_movie table: Each list is randomly assigned 5-10 movies.
closes #307
> feat: seeds for pivot tables

- app/utils/helpers.php
- resources/views/components/section.blade.php
1. when rendering multiple sections it complains that the `validateBreakpoint` and `generateSectionGridVariable`
- moved them to the `helpers` function
2. the little gradient was position relative to the page and not the component
- change from `absolute` to `sticky`
> fix: section component bugs

- app/Http/Controllers/Auth/NewPasswordController.php
- tests/Feature/Auth/PasswordResetTest.php
Found an inconsistency between the route name and some references to it.
> fix: replace route('login') with route('log-in')

- app/Http/Controllers/Auth/RegisteredUserController.php
Before this change, users could enter usernames with special characters such as `$h4ll0_€.` Now, usernames are restricted to only letters (A-Z, a-z) and numbers (0-9), ensuring consistency and better security.
> fix: Restrict username to Alphanumeric characters

- resources/views/components/review.blade.php
the content wouldn't clamp with the current layout. also renamed `description` to `content` to match the database and better describe the prop
> fix: review content clamp

- resources/views/components/section-header/link.blade.php
- resources/views/components/section-header/no-link.blade.php
not providing an `extraLabel` causes the site to crash. by checking with `@isset` instead we get the expected behavior
> fix: change `@if` to `@isset`

- routes/web.php
since we don't have an admin middleware yet (#357) this is causing the site to crash when accessing an `/admin` route
> fix: remove non existent admin middleware

- resources/views/admin/dashboard.blade.php
- resources/views/components/input/checkbox.blade.php
- resources/views/home.blade.php
Unchecked:
Checked:
And an example is in the admin dashboard view.
> feat: input checkbox

- package-lock.json
we have a duplicate key in package-lock.json that has been causing some issues
> fix: remove duplicate package-lock key

- app/Http/Controllers/ListController.php
- app/Models/MovieList.php
- resources/views/components/menu-item.blade.php
- resources/views/components/modal/divider.blade.php
- resources/views/components/modal/menu.blade.php
- resources/views/list.blade.php
- routes/web.php
closes #117
- render menu button only for owners of the list
- create modal with options:
- edit (to be implemented)
- change visibility (to be implemented)
- delete
- `destroy` method for deleting a list you are the owner of
- create `isOwnedBy` method on the `MovieList` model
- detached the divider from `modal.menu` and created its own component `modal.divider` because the styling wasn't working as intended
- some minor changes to `menu-item` to make it work with the modal
- log in (if you're not logged in you should not see the ellipsis icon)
- go to `/u/{username}/lists`'
- create a list
- try to delete the list
> feat: list settings menu

- app/Http/Controllers/ListController.php
- app/Http/Controllers/ReviewController.php
- app/Models/Review.php
- resources/views/components/input/error.blade.php
- resources/views/components/modal/menu.blade.php
- resources/views/list.blade.php
- resources/views/review.blade.php
- routes/web.php
closes #387 
- modal with conditional menu items
- delete review method
- reviews can be deleted by the author or an admin
- support for menu modal to display an error (visible in the preview)
- (also updated the list menu to display the error)
- `isWrittenBy` method on `Review` model 
- go to a review
- open the menu
- only report review should be visible
- log in
- go to a review you have created
- open the menu
- edit and delete should be visible
- try to delete the review
- log in to an admin account
- go to a review
- report and delete should be visible
- try to delete the review
> feat: review menu

- app/Http/Controllers/MovieController.php
- app/utils/helpers.php
- database/factories/ReviewFactory.php
- resources/views/movie.blade.php
- Fixed the ReviewsFactory to only use existing movies when generating reviews
- The delete and edit buttons are only visible for admin users
Note: Because of a tricky design, where the mobile and desktop designs differs a lot, I decided to make 1 version for mobile, and 1 version for desktop. Because of that there is a lot of duplicate code (which is not optional). If there is time later, I will fix it, but for now its important to get this in main.
I also decided to not include the "Show more" button to show more text for now because it is not prioritized. That will also be added if there is time.
closes #130
> feat: create info section movie view

- app/Http/Controllers/ReviewController.php
- resources/views/review.blade.php
- routes/web.php
closes #383 
- modal for editing a review
- `update` method in `Review` model
- open modal from the `review-menu` modal
- log in
- go to a review you have created
- try to edit it
> feat: update review modal

- app/Http/Controllers/ProfileController.php
- resources/views/components/profile.blade.php
- resources/views/profile.blade.php
closes #97 
- render the profile part of the profile view
- some changes to `<x-profile />` to fit the use case
- some changes to how the profile data is being rendered
- empty state
- admin buttons for admins visiting their own profile
- go to a random profile
- go to your own profile (while logged in)
- make yourself an admin to see the dashboard button
> feat: render profile section

- resources/views/components/section.blade.php
noticed lists rendered in a `<x-section />` with `scrollableOnMobile` was behaving very strangely
> fix: size of list children in section

- app/Http/Controllers/ProfileController.php
- resources/views/components/profile.blade.php
- resources/views/profile.blade.php
- routes/web.php
closes #103
- profile menu that displays different menu items depending on
- if the current user is an admin
- if you are on your own profile
- functionality for logging out
- functionality for making a user an admin
- go to your own profile
- try logging out
- ensure you're an admin
- go to someone else's profile who's not an admin
- make them an admin
> feat: profile menu

- app/Http/Controllers/ReportController.php
- resources/views/review.blade.php
- routes/web.php
closes #111 
- open report review modal and close the review menu
- `store` function in `ReportController`
- route for report review
- modal with form and error handling
- go to a review page
- click the menu
- click report review
- write a report longer than 255 characters and send (you must be logged in)
- you should see an error message
- write a shorter report and send
- you should be sent back to the review page
> feat: report review

- app/Http/Requests/Auth/LoginRequest.php
- database/migrations/0001_01_01_000000_create_users_table.php
- resources/views/auth/log-in.blade.php
closes #409 
- a banned user will be blocked from logging in
- an error message will be displayed saying how long they are blocked for
https://github.com/user-attachments/assets/e4af8d16-9139-43c6-be90-26d6dbb6df35
- log in with an unbanned account
- ensure it still works
- log out
- ban yourself
- try logging in again
- you should see the error message
> feat: disallow banned users from logging in

- database/factories/ReportFactory.php
- database/migrations/2025_01_30_122917_create_reports_table.php
currently you can set both a `review_id` and a `user_id` of a report at the same time. this is not how we intended the table to be used. so i've added a `CHECK` that ensures only one of the ids are set, not both and not neither. i also updated the factory accordingly
> fix: reports check

- app/Http/Controllers/ListController.php
- resources/views/lists.blade.php
- fix empty state on the lists page
- fix create list button size and placement
- rename `myLists` to `lists` as it's not just "my" lists
> fix: empty state lists view

- app/Http/Controllers/ProfileController.php
- resources/views/admin/reported-user.blade.php
- resources/views/components/ban-user-modal.blade.php
- resources/views/components/profile/simplified.blade.php
- resources/views/profile.blade.php
closes #419
- render `<x-ban-user-modal />` in `reported-user.blade.php`
- open modal on "ban user" click
- this button is replaced by text if the user already is banned
- also added this text for an admin visiting a banned users profile
- some minor design changes
https://github.com/user-attachments/assets/5a25be4d-7980-4d6c-8cc7-0510abd51915
> feat: ban user from reported user view
